[[CSRs]]
== Shadow Stack and Landing Pad CSRs

This chapter specifies the CSR state of the Zicfisslp extension.

=== Machine environment configuration registers (`menvcfg and menvcfgh`)

.Machine environment configuration register (`menvcfg`) for MXLEN=64
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'FIOM'},
  {bits:  3, name: 'WPRI'},
  {bits:  2, name: 'CBIE'},
  {bits:  1, name: 'CBCFE'},
  {bits:  1, name: 'CBZE'},
  {bits: 51, name: 'WPRI'},
  {bits:  1, name: 'SFCFIE'},
  {bits:  1, name: 'CFIE'},
  {bits:  1, name: 'HADE'},
  {bits:  1, name: 'PBMTE'},
  {bits:  1, name: 'STCE'},
], config:{lanes: 4, hspace:1024}}
....

The `CFIE` field (bit 60) controls whether Zicfisslp extension is available for
use in modes less privileged than M. When `CFIE` is 1, the `SFCFIE` field
(bit 59) enables forward-edge CFI at S-mode.

When `menvcfg.CFIE` bit is 0, the following rules apply to privilege modes less
privileged than M:

* Attempts to access the `ssp` CSR result in an illegal-instruction exception.
* Shadow stack instructions revert to the Zimop/Zcmop defined behavior.
* The `lpad` instruction executes as a no-op.
* The `UBCFIE`, `UFCFIE`, and `SPELP` fields in `sstatus` are read-only zero.
* The `CFIE` field in `henvcfg` is read-only zero.
* The `pte.xwr=010b` encoding in S-stage page tables is reserved.

[NOTE]
====
When the Zicfisslp extension is available for use at privilege mode less than
M, the operating system may use the `UBCFIE` and `UFCFIE` to selectively
enable the backward-edge and forward-edge CFI, respectively, for U-mode
applications.

When the Zicfisslp extension is available for use in S-mode, the operating
system may use shadow stacks at S-mode. If the operating system wants to use
forward-edge CFI in S-mode, then it should request the SEE to set the
`menvcfg.SFCFIE` field to 1 to enable it.

The set of controls described above allows for the separate enforcement of
backward-edge and forward-edge CFI at S-mode and at U-mode for each application.
====

=== Hypervisor environment configuration registers (`henvcfg and henvcfgh`)

.Hypervisor environment configuration register (`henvcfg`) for MXLEN=64
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'FIOM'},
  {bits:  3, name: 'WPRI'},
  {bits:  2, name: 'CBIE'},
  {bits:  1, name: 'CBCFE'},
  {bits:  1, name: 'CBZE'},
  {bits: 51, name: 'WPRI'},
  {bits:  1, name: 'SFCFIE'},
  {bits:  1, name: 'CFIE'},
  {bits:  1, name: 'HADE'},
  {bits:  1, name: 'PBMTE'},
  {bits:  1, name: 'STCE'},
], config:{lanes: 4, hspace:1024}}
....

The `CFIE` field (bit 60) controls whether the Zicfisslp extension is available
for use in VS and VU modes. When `menvcfg.CFIE` is 0, `henvcfg.CFIE` is
read-only zero.

When `henvcfg.CFIE` bit is 0, then at privilege modes VS and VU:

* Attempts to access the `ssp` CSR result in an virtual-instruction exception.
* Shadow stack instructions revert to the Zimop/Zcmop defined behavior.
* The `lpad` instruction executes as a no-op.
* The `UBCFIE`, `UFCFIE`, and `SPELP` fields in `sstatus` (really `vsstatus`) are
  read-only zero.
* The `pte.xwr=010b` encoding in VS-stage page tables is reserved.

When `henvcfg.CFIE` is 1, the `henvcfg.SFCFIE` field (bit 59) enables
forward-edge CFI at VS-mode.

=== Machine status registers (`mstatus`)

.Machine-mode status register (`mstatus`) for RV64
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SIE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'MIE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SPIE'},
  {bits:  1, name: 'UBE'},
  {bits:  1, name: 'MPIE'},
  {bits:  1, name: 'SPP'},
  {bits:  2, name: 'VS[1:0]'},
  {bits:  2, name: 'MPP[1:0]'},
  {bits:  2, name: 'FS[1:0]'},
  {bits:  2, name: 'XS[1:0]'},
  {bits:  1, name: 'MPRV'},
  {bits:  1, name: 'SUM'},
  {bits:  1, name: 'MXR'},
  {bits:  1, name: 'TVM'},
  {bits:  1, name: 'TW'},
  {bits:  1, name: 'TSR'},
  {bits:  1, name: 'UFCFIE'},
  {bits:  1, name: 'UBCFIE'},
  {bits:  1, name: 'SPELP'},
  {bits:  1, name: 'MPELP'},
  {bits:  5, name: 'WPRI'},
  {bits:  2, name: 'UXL[1:0]'},
  {bits:  2, name: 'SXL[1:0]'},
  {bits:  1, name: 'SBE'},
  {bits:  1, name: 'MBE'},
  {bits: 25, name: 'WPRI'},
  {bits:  1, name: 'SD'},
], config:{lanes: 4, hspace:1024}}
....

The `UFCFIE` (bit 23) and `UBCFIE` (bit 24) are WARL fields that, when set to 1,
enable forward-edge and backward-edge CFI, respectively, in U-mode.

The `SPELP` (bit 25) and `MPELP` (bit 26) WARL fields are hold the previous
`ELP`, and are updated as specified in <<FORWARD_TRAPS>>. The `xPELP` fields are
encoded as follows:

* 0 - `NO_LP_EXPECTED` - no landing pad instruction expected.
* 1 - `LP_EXPECTED` - a landing pad instruction is expected.

=== Supervisor status registers (`sstatus`)

.Supervisor-mode status register (`sstatus`) when `SXLEN=64`
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SIE'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'SPIE'},
  {bits:  1, name: 'UBE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SPP'},
  {bits:  2, name: 'VS[1:0]'},
  {bits:  2, name: 'WPRI'},
  {bits:  2, name: 'FS[1:0]'},
  {bits:  2, name: 'XS[1:0]'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SUM'},
  {bits:  1, name: 'MXR'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'UFCFIE'},
  {bits:  1, name: 'UBCFIE'},
  {bits:  1, name: 'SPELP'},
  {bits:  6, name: 'WPRI'},
  {bits:  2, name: 'UXL[1:0]'},
  {bits: 29, name: 'WPRI'},
  {bits:  1, name: 'SD'},
], config:{lanes: 4, hspace:1024}}
....

When `menvcfg.CFIE` is 1, access to the following fields accesses the homonymous
field of the `mstatus` register. When `menvcfg.CFIE` is 0, these fields are
read-only zero.

* `UFCFIE` (bit 23).
* `UBCFIE` (bit 24).
* `SPELP` (bit 25).

=== Virtual supervisor status registers (`vsstatus`)

.Virtual supervisor status register (`vsstatus`) when `VSXLEN=64`
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SIE'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'SPIE'},
  {bits:  1, name: 'UBE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SPP'},
  {bits:  2, name: 'VS[1:0]'},
  {bits:  2, name: 'WPRI'},
  {bits:  2, name: 'FS[1:0]'},
  {bits:  2, name: 'XS[1:0]'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SUM'},
  {bits:  1, name: 'MXR'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'UFCFIE'},
  {bits:  1, name: 'UBCFIE'},
  {bits:  1, name: 'SPELP'},
  {bits:  6, name: 'WPRI'},
  {bits:  2, name: 'UXL[1:0]'},
  {bits: 29, name: 'WPRI'},
  {bits:  1, name: 'SD'},
], config:{lanes: 4, hspace:1024}}
....

The `vsstatus` register is VS-mode's version of `sstatus`, and the Zicfisslp
extension introduces the following fields.

* `UFCFIE` (bit 23)
* `UBCFIE` (bit 24)
* `SPELP` (bit 25)

When `menvcfg.CFIE` is 0, these fields are read-only zero. When `menvcfg.CFIE` is
1 and `henvcfg.CFIE` is 0, these fields are read-only zero in `sstatus` (really
`vsstatus`) when V=1.

[NOTE]
====
The `vsstatus` and `henvcfg` CSR for a virtual machine may be restored in any
order. The state of `henvcfg.CFIE` does not prevent access to the bits introduced
in `vsstatus` when the CSR is accessed in HS-mode.
====

=== Machine Security Configuration (`mseccfg`)

.Machine security configuration register (`mseccfg`) when `MXLEN=64`
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'MML'},
  {bits:  1, name: 'MMWP'},
  {bits:  1, name: 'RLB'},
  {bits:  5, name: 'WPRI'},
  {bits:  1, name: 'USEED'},
  {bits:  1, name: 'SSEED'},
  {bits:  1, name: 'MFCFIE'},
  {bits:  6, name: 'SSPMP'},
  {bits: 47, name: 'WPRI'},
], config:{lanes: 4, hspace:1024}}
....

A new WARL field `sspmp` is defined the `mseccfg` CSR to identify a PMP entry
as the shadow stack memory region for M-mode accesses. The rules enforced by
PMP for M-mode shadow stack memory accesses are outlined in <<PMP_SS>>.

The `MFCFIE` (bit 10) is a WARL field that when set to 1 enables forward-edge
CFI at M-mode.

=== Shadow stack pointer (`ssp`) 

The `ssp` CSR is an unprivileged read-write (URW) CSR that reads and writes `XLEN`
low order bits of the shadow stack pointer (`ssp`). There is no high CSR defined
as the `ssp` is always as wide as the `XLEN` of the current privilege mode.

When `menvcfg.CFIE` is 0, an attempt to access `ssp` in a mode other than M-mode
raises an illegal instruction exception. When `sstatus.UBCFIE` is 0, an attempt
to access `ssp` in U-mode raises an illegal-instruction exception.

[NOTE]
====
Access to `ssp` at S-mode is not dependent on `sstatus.UBCFIE`, allowing an
operating system to context switch U-mode `ssp` for each application as needed.
====

When `menvcfg.CFIE` is 1 but `henvcfg.CFIE` is 0, accessing `ssp` in VS-mode
raises a virtual-instruction exception. 

When both `menvcfg.CFIE` and `henvcfg.CFIE` are 1 but `vsstatus.UBCFIE` is 0, 
accessing `ssp` in VU-mode raises an illegal-instruction exception.
