[[forward]]
== Forward-edge control-flow integrity

The forward-edge CFI introduces landing pad instructions that enable software to
indicate valid targets for indirect calls and indirect jumps in a program.

A landing pad instruction (`lpcll`) is defined as the instruction that must be
placed at the program locations that can be valid targets of indirect jumps or
calls.

To enforce that the target of an indirect call or indirect jump must be a valid
landing pad instruction, the hart maintains an expected landing pad (`ELP`) state
to determine if a landing pad instruction is required at the target of an
indirect call or jump. The `ELP` state can be one of:

* 0 - `NO_LP_EXPECTED`
* 1 - `LP_EXPECTED`

The Zisslpcfi extension determines if an indirect call or an indirect jump must
land on landing pad, as specified in <<IND_CALL_JMP>>. If `is_lp_expected` is 1,
an indirect call or jump updates the `ELP` to `LP_EXPECTED`.

[[IND_CALL_JMP]]
.Landing pad expected determination
[source, ruby]
----
    is_indirect_call_jump = ( (JALR || C.JR || C.JALR) &&
                              (rs1 != x1) && (rs1 != x5) ) ? 1 : 0;
    is_sw_guarded_jump = ( JALR && rd == x7 && rs1 == x7 ) ? 1 : 0;
    is_lp_expected = is_indirect_call_jump & ~is_sw_guarded_jump;
----

When `ELP` is set to `LP_EXPECTED` and the next instruction in the instruction
stream is not 4-byte aligned, or is not a `lpcll`, or if the label encoded in
the `lpcll` does not match the lower label in `lpl` register, then an illegal-
instruction exception is raised. If the next instruction in the instruction
stream is 4-byte aligned and is a `lpcll` with its label matching the lower
label in `lpl` register, then the `ELP` updates to `NO_LP_EXPECTED`.

[NOTE]
====
The tracking of `ELP` and the requirement for valid landing pad instructions
at the target of indirect call and jump enables a processor implementation to
significantly reduce or to prevent speculation to non-landing-pad instructions.
Constraining speculation using this technique, greatly reduces the gadget space
and increases the difficulty of using techniques such as branch-target-injection,
also known as Spectre variant 2, which use speculative execution to leak data
through side channels.
====

When the indirect branch using `JALR` encodes both `rd` and `rs1` as `x7`, the
branch is termed a software guarded branch. Such branches do not need to land on
a landing pad and thus do not update `ELP`. Such branches must be used by a
program only when the compiler or the program has emitted code to explicitly
verify that the target held in `x7` is a valid target for that branch.

[NOTE]
====
Software guarded branches are expected to be used by compilers for generating
code for constructs like switch-cases. When using the software guarded branches,
the compiler is required to ensure it has full control on the possible jump
targets (e.g., by obtaining the targets from a read-only table in memory and
performing bounds checking on the index into the table, etc.).

While software guarded branches may be secured using such compiler generated
checks, in some cases they may be susceptible. For example, where software can
be interrupted, the `x7` register may be spilled to mutable memory by the
interrupt or signal handler. The memory location where the register is spilled
may be susceptible to modifications. Therefore, software should opt to use the
software guarded branches only where such threats are not applicable or are
mitigated.
====

By default a landing pad allows an indirect call/jump to land on any `lpcll` in
the program, which significantly reduces the number of valid targets for an
indirect call/jump. Labeling of the landing pads enables software to achieve
greater precision in pairing up indirect call/jump sites sites with valid
targets. To support labeled landing pads, the indirect call/jump sites establish
an expected landing pad label in the landing pad label (`lpl`) register. If the
target of the indirect call/jump is a valid landing pad instruction, the expected
label established in the `lpl` is matched with the target's label. If a mismatch
is detected then the label check instruction causes an illegal-instruction
exception.

Each landing pad may be labeled with a label that can be up to 25-bits wide. The
`lpl` has three subfields - a 9-bit lower label (`LL`), an 8-bit middle label
(`ML`), and an 8-bit upper label (`UL`).

The `lpsll` instruction is used to set the expected `LL` in the `lpl` and to
set the `ML` and `UL` fields of `lpl` to 0. The `lpsml` instruction is used to
set the expected `ML` in `lpl` while keeping the `UL` and `LL` fields
unchanged. The `lpsul` instruction is used to set the expected `UL` in `lpl`
while keeping the `LL` and `ML` fields unchanged. The values to be set are
embedded as immediate fields in these instructions.

The `lpcll` instruction embeds a 9-bit immediate field. The instruction compares
this value to the `LL` in `lpl` and on a mismatch causes an illegal-instruction
exception.

For label widths up to 17-bits, a companion instruction `lpcml` is provided. The
`lpcml` embeds a 8-bit immediate value that is compared to the `ML` and on a
mismatch causes an illegal-instruction exception.

For label widths greater than 17-bits, a second companion instruction `lpcul` is
provided. The `lpcul` embeds a 8-bit immediate value that is compared to the `UL`
and on a mismatch causes an illegal-instruction exception.

=== Forward-edge CFI Instructions

The forward-edge CFI introduces the following instructions for landing
pad operations:

* Landing pad (See <<LP_INST>>)
** `lpcll`

* Label matching (See <<LBL_MATCH>>)
** `lpcml` and `lpcul`

* Setup landing pad label register (See <<LBL_SET>>)
** `lpsll`, `lpsml`, and `lpsul`

These instructions are encoded using the SYSTEM major opcode and
the `mop.rr` encodings defined by the Zimop extension.

When a Zimop encoding is not used by the Zisslpcfi extension then the
instruction follows its Zimop defined behavior.

=== Forward-edge CFI enables

When privilege mode is M, the forward-edge CFI is active when `MFCFIE` is 1 in
`mseccfg` register.

When `menvcfg.CFIE` is 0, Zisslpcfi is not enabled for privilege modes less than
M, and forward-edge CFI is not active at privilege levels less than M.

When `V=0` and `menvcfg.CFIE` is 1, then forward-edge CFI is active in S-mode if
`menvcfg.SFCFIE` is 1 and is active in U-mode if `mstatus.UFCFIE` is 1.

When `henvcfg.CFIE` is 0, Zisslpcfi is not enabled for use when `V=1`.

When `V=1` and both `menvcfg.CFIE` and `henvcfg.CFIE` are 1, then forward-edge CFI
is active at VS-mode if `henvcfg.SFCFIE` is 1 and is active at VU-mode if
`vsstatus.UFCFIE` is 1.

The term `xFCFIE` is used to determine if forward-edge CFI is active at
privilege mode `x` and is defined as follows:

.`xFCFIE` determination
[source, ruby]
----
if ( privilege == M-mode )
    xFCFIE = mseccfg.MFCFIE
else if ( menvcfg.CFIE == 1 && V == 0 && privilege == S-mode )
    xFCFIE = menvcfg.SFCFIE
else if ( menvcfg.CFIE == 1 && V == 0 && privilege == U-mode )
    xFCFIE = mstatus.UFCFIE
else if ( menvcfg.CFIE == 1 && henvcfg.CFIE == 1 && V == 1 && privilege == S-mode )
    xFCFIE = henvcfg.SFCFIE
else if ( menvcfg.CFIE == 1 && henvcfg.CFIE == 1 && V == 1 && privilege == U-mode )
    xFCFIE = vsstatus.UFCFIE
else
    xFCFIE = 0
----

When forward-edge CFI is not active (`xFCFIE = 0`):

* The hart does not update the expected landing pad (`ELP`) state on an
  indirect call or jump, and does not require the instruction at the target of
  an indirect call or jump to be a landing pad instruction.
* The hart does not update the expected landing pad (`ELP`) when `lpcll`
  is executed.
* The instructions defined for forward-edge CFI revert to their Zimop-defined
  behavior and do not set or check landing pad labels.

[[LP_INST]]
=== Landing pad instruction

`lpcll` is the valid landing pad instruction at target of indirect jumps and
indirect calls. When a forward-edge CFI is active, the instruction causes an
illegal-instruction exception if it is not placed at a 4-byte aligned `pc`.
The `lpcll` has the lower landing pad label embedded in the `LLPL` field.
`lpcll` causes an illegal-instruction exception if the `LLPL` field in the
instruction does not match the `lpl.LL` field.

[wavedrom, , ]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:'00000'},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  9, name: 'imm9', attr:['LLPL']},
  {bits:  1, name: 'typ', attr:['1']},
  {bits:  7, name: '1000001', attr:['lpcll']},
], config:{lanes: 1, hspace:1024}}
....

When the instruction causes an illegal-instruction exception, the `ELP` does not
change. The behavior of the trap caused by this illegal-instruction exception is
specified in section <<FORWARD_TRAPS>>.

The operation of the `lpcll` instruction is as follows:

.`lpcll` operation
[source, ruby]
----
If xFCFIE != 0
    // If PC not 4-byte aligned then illegal-instruction
    if pc[1:0] != 0
        Cause illegal-instruction exception
    // If lower landing pad label not matched -> illegal-instruction
    else if (inst.LLPL != lpl.LL)
        Cause illegal-instruction exception
    else
        ELP = NO_LP_EXPECTED
else
    [rd] = 0;
endif
----

Whereas `lpcll` is the only instruction that can execute when `ELP` is
`LP_EXPECTED`, `lpcll` can also execute when `ELP` is `NO_LP_EXPECTED`.

[NOTE]
====
Concatenation of two instructions `A` and `B` can accidentally form a valid
landing pad in the program. For example, consider a 32-bit instruction where the
bytes 3 and 2 have a pattern of `4073h` or `c073h` (for example, the immediate
fields of a `lui`, `auipc`, or a `jal` instruction), followed by a 16-bit or a
32-bit instruction with a second byte with pattern of `83` (for example, an
`addi x6, x0, 1`).

The `lpcll` requires a 4-byte alignment. When patterns that can accidentaly form
a valid landing pad are detected, the assembler/linker can force instruction `A`
to be aligned to a 4-byte boundary to force the unintended `lpcll` pattern to
become misaligned and thus not a valid landing pad.
====

[[LBL_MATCH]]
=== Label matching instructions

The `lpcml` instruction matches the 8-bit wide middle label in its `MLPL` field with
the `lpl.ML` field and causes an illegal-instruction exception on a mismatch. The
`lpcml` is not a valid target for an indirect call or jump.

The `lpcul` instruction matches the 8-bit wide upper label in its `ULPL` field with
the `lpl.UL` field and causes an illegal-instruction exception on a mismatch. The
`lpcul` is not a valid target for an indirect call or jump.

[wavedrom, , ]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:'00000'},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  8, name: 'imm8', attr:['MLPL','ULPL']},
  {bits:  2, name: 'typ', attr:['01','11']},
  {bits:  7, name: '1000011', attr:['lpcml','lpcul']},
], config:{lanes: 1, hspace:1024}}
....

The operation of the `lpcml` instruction is as follows:

.`lpcml` operation
[source, ruby]
----
If xFCFIE != 0
    if (lpl.ML != inst.MLPL)
        cause illegal-instruction exception
else
    [dst] = 0;
endif
----

The operation of the `lpcul` instruction is as follows:

.`lpcul` operation
[source, ruby]
----
If xFCFIE != 0
    if (lpl.UL != inst.ULPL)
        cause illegal-instruction exception
else
    [dst] = 0;
endif
----

[[LBL_SET]]
=== Setting up landing pad label register

Before performing an indirect call or indirect jump to a labeled landing pad,
the `lpl` is loaded with the expected landing pad label. The label is a constant
encoded into the instructions used to setup the `lpl`.

[wavedrom, , ]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:'00000'},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  9, name: 'imm9', attr:['LLPL']},
  {bits:  1, name: 'typ', attr:['0']},
  {bits:  7, name: '1000001', attr:['lpsll']},
], config:{lanes: 1, hspace:1024}}
....

[wavedrom, , ]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:'00000'},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  8, name: 'imm8', attr:['MLPL','ULPL']},
  {bits:  2, name: 'typ', attr:['00','10']},
  {bits:  7, name: '1000011', attr:['lpsml','lpsul']},
], config:{lanes: 1, hspace:1024}}
....

The `lpsll` instruction is used to set the value of the lower label (`LL`) field
of the `lpl`. In addition to setting `LL`, the instruction sets the `ML` and
`UL` fields to 0.

The operation of this instruction is as follows:

.`lpsll` operation
[source, ruby]
----
If xFCFIE == 1
   lpl.LL = inst.LLPL
   lpl.ML = lpl.UL = 0
else
   [rd] = 0;
endif
----

[NOTE]
====
The compiler may emit the following instruction sequence at indirect call/jump
sites to set up the landing pad label register when using labels up to 9 bits
wide:

[source, ruby]
foo:
    :
    # x10 is expected to have address of function bar()
    lpsll $0x1de    # setup lpl.LL with value 0x1de
    jalr %ra, %x10
    :

The compiler may emit the following instruction sequence at the indirect
call/jump targets, such as function entry points, to create a landing pad:

[source, ruby]
bar:
    lpcll $0x1de    # Verifies that lpl.LL matches 0x1de
    :               # continue if landing pad checks succeed
====

The `lpsml` instruction is used to set the value of the middle label (`ML`) field
of the `lpl`. The `UL` and `LL` fields of the `lpl` remain unchanged. This
instruction is typically used when labels wider than 9-bit are required.

The operation of this instruction is as follows:

.`lpsml` operation
[source, ruby]
----
If xFCFIE == 1
   lpl.ML = inst.MLPL
else
   [rd] = 0;
endif
----

[NOTE]
====
The compiler may emit the following instruction sequence at indirect call/jump
sites to set up the landing pad label register when using labels up to 17 bits
wide:

[source, ruby]
foo:
    :
    # x10 is expected to have address of function bar()
    lpsll $0x1de    # setup lpl.LL with value 0x1de
    lpsml $0x17     # setup lpl.ML with value 0x17
    jalr %ra, %x10
    :

The compiler may emit the following instruction sequence at the indirect
call/jump targets, such as function entry points, to create a landing pad:

[source, ruby]
bar:
    lpcll $0x1de    # Verifies that lpl.LL matches 0x1de
    lpcml $0x17     # Verifies that lpl.ML matches 0x17
    :               # continue if landing pad checks succeed
====

A `lpsul` instruction is used to set the value of upper label (`UL`) field the
`lpl`. The `LL` and `ML` fields remain unchanged. This instruction is typically
used when labels wider than 17-bit are required.

The operation of this instruction is as follows:

.`lpsul` operation
[source, ruby]
----
If xFCFIE == 1
   lpl.UL = inst.ULPL
else
   [rd] = 0;
endif
----

[NOTE]
====
The compiler may emit the following instruction sequence at indirect call/jump
sites to set up the landing pad label register when using labels up to 25 bits
wide:

[source, ruby]
foo:
    :
    # x10 is expected to have address of function bar()
    lpsll $0x1de    # setup lpl.LL with value 0x1de
    lpsml $0x17     # setup lpl.ML with value 0x17
    lpsul $0x13     # setup lpl.UL with value 0x13
    jalr %ra, %x10
    :

The compiler may emit the following instruction sequence at the indirect
call/jump targets, such as function entry points, to create a landing pad:

[source, ruby]
bar:
    lpcll $0x1de    # Verifies that lpl.LL matches 0x1de
    lpcml  $0x17    # Verifies that lpl.ML matches 0x17
    lpcul  $0x13    # Verifies that lpl.ML matches 0x13
    :               # continue if landing pad checks succeed
====

[NOTE]
====

The `lpcml` and `lpcul` need not occur together or in that order. Use of a
`lpcul` does not require a preceding or a following `lpcml`. The following
sequences are also a valid label check sequence:

[source, ruby]
bar:
    lpcll $lwr_label
    lpcul $upr_label
    :

[source, ruby]
bar:
    lpcll $lwr_label
    lpcul $upr_label
    lpcml $mdl_label
    :

A `lpsll` sets the `LL` and also initializes the `ML` and `UL` fields to zero.
If the label to be assigned has zero for `ML` and `UL`, then there is no need to
explicitly set them to zero using a `lpsml` or `lpsul`. `lpsml` and `lpsul`
can be used independently and in any order. The use of a `lpsul` does not
require a preceding or following `lpsml`.

====

[[FORWARD_TRAPS]]
=== Preserving expected landing pad state on traps

A trap may need to be delivered to the same or to a higher privilege mode upon
completion of `JALR`/`C.JALR`/`C.JR`, but before the instruction at the target
of indirect call/jump was decoded, due to:

* Asynchronous interrupts.
* Synchronous exceptions with priority lower than that of an illegal-instruction
  exception (See Table 3.7 of Privileged Specification cite:[PRIV]).
* By the illegal-instruction exception due to the instruction at the target not
  being an `lpcll` instruction, or the `lpcll` instruction not being 4-byte
  aligned, or due to the `LLPL` encoded in the `lpcll` not matching the `LL`
  field of `lpl`.

In such cases, the `ELP` prior to the trap, the previous `ELP`, may be
`LP_EXPECTED`.

To store the previous `ELP` state on trap delivery to M-mode, a `MPELP` bit
is provided in the `mstatus` CSR to hold the previous `ELP`.

To store the previous `ELP` state on trap delivery to S/HS-mode, a `SPELP`
bit is provided in the `mstatus` CSR to hold the previous `ELP`. The `SPELP`
bit in `mstatus` can be accessed through the `sstatus` CSR.

To store the previous `ELP` state on traps to VS-mode, a `SPELP` bit is
defined in the `vsstatus` (VS-modes version of `sstatus`) to hold the previous
`ELP`.

When a trap is taken into privilege mode `x`, the `xPELP` is set to `ELP` and
`ELP` is set to `NO_LP_EXPECTED`.

An `MRET` or `SRET` instruction is used to return from a trap in M-mode or
S-mode, respectively. When executing an `xRET` instruction, the `ELP` is set to
`xPELP`, and the `xPELP` is set to `NO_LP_EXPECTED`.

[NOTE]
====
The trap handler in privilege mode `x` must save the `xPELP` bit and the `lpl`
register before performing an indirect call/jump. If the privilege mode `x`
can respond to interrupts, then the trap handler should also save these values
before enabling interrupts.

The trap handler in privilege mode `x` must restore the saved `xPELP` bit and
the `lpl` register before executing the `xRET` instruction to return from a
trap.
====
