
[[backward]]
== Shadow Stack (Zicfiss)

To enforce backward-edge control-flow integrity, the Zicfiss extension
introduces a shadow stack. A shadow stack is a second stack used to store a
shadow copy of the return address in the link register if it needs to be spilled.

The shadow stack, similar to the regular stack, grows downwards, i.e. from higher
addresses to lower addresses. Each entry on the shadow stack is `XLEN` wide and
holds the link register value. The `ssp` points to the top of the shadow stack,
i.e. address of the last element stored on the shadow stack.

When Zicfiss is enabled, each function that needs to spill the link
register (e.g., non-leaf functions) stores the link register value to the regular
stack and a shadow copy of the link register value to the shadow stack when the
function is entered (the prologue). When such a function need to return (the
epilogue), the function loads the link register from the regular stack and
the shadow copy of the link register from the shadow stack. The link register
value from the regular stack and the shadow link register value from the shadow
stack are compared. A mismatch of the two values is indicative of a subversion
of the return address control variable and causes an integrity-fault exception
with *tval set to "shadow stack fault (code=3)". The integrity-fault exception
caused by the shadow stack fault is lower in priority than the load access fault
exception.

The Zicfiss extension introduces the following instructions:

* Push to and pop from the shadow stack (See <<SS_PUSH_POP>>)
** `sspush x1`, `c.sspush x1`, and `sspush x5`
** `sspopchk x1`, `sspopchk x5`, and `c.sspopchk x5`
** `ssload x1`, and `ssload x5`
** `ssincp`, and `c.ssincp`

* Read the value of `ssp` into a register (See <<SSP_READ>>)
** `ssprr`

* Perform atomic swap from a shadow stack location (See <<SS_SWAP>>)
** `ssamoswap`

The 32-bit instructions are encoded using the `SYSTEM` major opcode and using
the `mop.r.0`, `mop.r.1`, and `mop.rr.0` encodings defined by the Zimop
extension.

The 16-bit instructions are encoded using the `C.LUI` major opcode and using
the `c.mop.0`, `c.mop.1` and `c.mop.2` encodings defined by the Zcmop extension.

When a Zimop encoding is not used by the Zicfiss extension then the
instruction follows its Zimop defined behavior.

== Zicfiss CSRs

This chapter specifies the CSR state of the Zicfiss extensions.

=== Machine environment configuration registers (`menvcfg and menvcfgh`)

.Machine environment configuration register (`menvcfg`) for MXLEN=64
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'FIOM'},
  {bits:  2, name: 'WPRI'},
  {bits:  1, name: 'SSE'},
  {bits:  2, name: 'CBIE'},
  {bits:  1, name: 'CBCFE'},
  {bits:  1, name: 'CBZE'},
  {bits: 53, name: 'WPRI'},
  {bits:  1, name: 'HADE'},
  {bits:  1, name: 'PBMTE'},
  {bits:  1, name: 'STCE'},
], config:{lanes: 4, hspace:1024}}
....

Zicfiss extension introduces the `SSE` field (bit 3) in `menvcfg`. When
`SSE` field is 1, the Zicfiss extension is enabled in S-mode. When `SSE`
field is 0, the Zicfiss extension is not enabled in S-mode and the following
rules apply to privilege modes less than M.

* Attempts to access the `ssp` CSR raise an illegal-instruction exception.
* The 32-bit Zicfiss instructions revert to their Zimop defined behavior.
* The 16-bit Zicfiss instructions revert to their Zcmop defined behavior.
* The `pte.xwr=010b` encoding in S-stage page tables is reserved.
* The `henvcfg.SSE` and `senvcfg.SSE` fields are read-only zero.

=== Supervisor environment configuration registers (`senvcfg`)

.Supervisor environment configuration register (`senvcfg`)
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'FIOM'},
  {bits:  2, name: 'WPRI'},
  {bits:  1, name: 'SSE'},
  {bits:  2, name: 'CBIE'},
  {bits:  1, name: 'CBCFE'},
  {bits:  1, name: 'CBZE'},
], config:{lanes: 1, hspace:1024}}
....

Zicfiss extension introduces the `SSE` field (bit 2) in `senvcfg`. When
`SSE` field is 1, the Zicfiss extension is enabled in VU/U-mode. When `SSE`
field is 0, the Zicfiss extension is not enabled in VS/U-mode and the following
rules apply:

* Attempts to access the `ssp` CSR raise an illegal-instruction exception.
* The 32-bit Zicfiss instructions revert to their Zimop defined behavior.
* The 16-bit Zicfiss instructions revert to their Zcmop defined behavior.

=== Hypervisor environment configuration registers (`henvcfg and henvcfgh`)

.Hypervisor environment configuration register (`henvcfg`) for MXLEN=64
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'FIOM'},
  {bits:  2, name: 'WPRI'},
  {bits:  1, name: 'SSE'},
  {bits:  2, name: 'CBIE'},
  {bits:  1, name: 'CBCFE'},
  {bits:  1, name: 'CBZE'},
  {bits: 53, name: 'WPRI'},
  {bits:  1, name: 'HADE'},
  {bits:  1, name: 'PBMTE'},
  {bits:  1, name: 'STCE'},
], config:{lanes: 4, hspace:1024}}
....

Zicfiss extension introduces the `SSE` field (bit 2) in `henvcfg`. When
`SSE` field is 1, the Zicfiss extension is enabled in VS-mode. When `SSE`
field is 0, the Zicfiss extension is not enabled in VS-mode and the following
rules apply when `V=1`.

* Attempts to access the `ssp` CSR raise an illegal-instruction exception.
* The 32-bit Zicfiss instructions revert to their Zimop defined behavior.
* The 16-bit Zicfiss instructions revert to their Zcmop defined behavior.
* The `pte.xwr=010b` encoding in VS-stage page tables is reserved.
* The `senvcfg.SSE` field is read-only zero.

=== Shadow stack pointer (`ssp`)

The `ssp` CSR is an unprivileged read-write (URW) CSR that reads and writes `XLEN`
low order bits of the shadow stack pointer (`ssp`). There is no high CSR defined
as the `ssp` is always as wide as the `XLEN` of the current privilege mode.

=== Machine Security Configuration (`mseccfg`)

.Machine security configuration register (`mseccfg`) when `MXLEN=64`
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'MML'},
  {bits:  1, name: 'MMWP'},
  {bits:  1, name: 'RLB'},
  {bits:  5, name: 'WPRI'},
  {bits:  1, name: 'USEED'},
  {bits:  1, name: 'SSEED'},
  {bits:  1, name: 'WPRI'},
  {bits:  6, name: 'SSPMP'},
  {bits: 47, name: 'WPRI'},
], config:{lanes: 4, hspace:1024}}
....

The Zicfiss extension introduces the `SSPMP` WARL field in `mseccfg`. The
`SSPMP` field identifies a PMP entry as the shadow stack memory region for
M-mode use. The rules enforced by PMP for M-mode shadow stack memory accesses
are specified in <<PMP_SS>>.

=== Shadow-Stack-Enabled (SSE) state

The term `xSSE` is used to determine if backward-edge CFI using shadow stacks
provided by the Zicfiss extension is enabled at a privilege mode and it is
determined as follows:

.`xSSE` determination
[width=100%]
[%header, cols="^4,^12"]
|===
|Privilege Mode| xLPE
|  M           | `1`
|  S or HS     | `menvcfg.SSE`
|  VS          | `henvcfg.SSE`
|  U or VU     | `senvcfg.SSE`
|===

[NOTE]
====
Activating Zicfiss in U-mode must be done explicitly per process. Not activating
Zicfiss at U-mode for a process when that application is not compiled with
Zicfiss allows it to invoke shared libraries that may contain Zicfiss
instructions. The Zicfiss instructions in the shared library revert to their
Zimop/Zcmop-defined behavior in this case.

When Zicfiss is enabled in S-mode it is benign to use an operating system that is
not compiled with Zicfiss instructions. Such an operating system that does
not use backward-edge CFI for S-mode execution may still activate Zicfiss for
U-mode applications.

When Zicfiss is implemented, the extension is always enabled in M-mode. However,
it is benign to use M-mode firmware that has not been compiled with Zicfiss
instructions. Such M-mode firmware that does not use backward-edge CFI for
M-mode execution may still enable the use of Zicfiss by lower privilege modes.

When programs that use Zicfiss instructions are installed on a processor that
supports the Zicfiss extension but the extension is not enabled at the privilege
mode where the program executes, the program continues to function correctly but
without backward-edge CFI protection as the Zicfiss instructions will revert to
their Zimop/Zcmop-defined behavior.

When programs that use Zicfiss instructions are installed on a processor that
does not support the Zicfiss extension but supports the Zimop and Zcmop
extensions, the programs continues to function correctly but without
backward-edge CFI protection as the Zicfiss instructions will revert to their
Zimop/Zcmop-defined behavior.

On processors that do not support Zimop/Zcmop extensions, all Zimop/Zcmop code
points including those used for Zicfiss instructions may cause an
illegal-instruction exception. Execution of programs that use these
instructions on such machines is not supported.
====

[[SS_PUSH_POP]]
=== Push to and Pop from the shadow stack

A shadow stack push operation is defined as decrement of the `ssp` by `XLEN`
followed by a write of the link register at the new top of the shadow stack.
A shadow stack pop operation is defined as a `XLEN` wide read from the
current top of the shadow stack followed by an increment of the `ssp` by
`XLEN`.

[wavedrom, ,svg]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:[`00000`,'00001','00101','00000','00000']},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  5, name: 'rs1', attr:[`00000`,'00000','00000', '00001', '00101']},
  {bits: 12, name: '100000011100', attr:[`ssincp`, 'ssload  x1','ssload  x5','sspopchk x1','sspopchk x5']},
], config:{lanes: 1, hspace:1024}}
....

[wavedrom, ,svg]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:['00000']},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  5, name: 'rs1', attr:['00000']},
  {bits:  5, name: 'rs2', attr:['00001', '00101']},
  {bits:  7, name: '1000001', attr:['sspush x1','sspush x5']},
], config:{lanes: 1, hspace:1024}}
....

[wavedrom, ,svg]
....
{reg: [
  {bits:  2, name: 'op', attr:'C1'},
  {bits:  5, name: '00000'},
  {bits:  5, name: 'rs1', attr:['00001','00101']},
  {bits:  1, name: '0'},
  {bits:  3, name: '011', attr:['c.sspush x1', 'c.sspopchk x5']},
], config:{lanes: 1, hspace:1024}}
....

Only `x1` and `x5` encodings are supported as `rd` for `ssload`.
Only `x1` and `x5` encodings are supported as `rs1` for `sspopchk`.
Only `x1` and `x5` encodings are supported as `rs2` for `sspush`.

Zicfiss provides 16-bit versions of the `sspush x1` and `sspopchk x5`
instructions using the Zcmop encodings. The `c.ssincp`, `c.sspush x1` and the
`c.sspopchk x5` instructions are encoded using the `C.LUI` major opcode and
using the `c.mop.0`, `c.mop.1`, and `c.mop.2` encodings.

The `c.sspush x1` expands to `sspush x1` and `c.sspopchk x5` expands to
`sspopchk x5`.

Usually programs with a shadow stack push the return address onto the regular
stack as well as the shadow stack in the function prologue of non-leaf
functions. Such programs when returning from the non-leaf function pop the link
register from the regular stack and pop a shadow copy of the link register from
the shadow stack. The two values are then compared. If the values do not match
it is indicative of a corruption of the return address variable on the regular
stack.

The `sspush` instruction and its compressed form `c.sspush` can be used, to push
a link register on the shadow stack.

The `sspopchk` instruction and its compressed form `c.sspopchk` can be used to
pop the shadow return address value from the shadow stack and check that the
value matches the contents of the link register and if not cause an
integrity-fault exception with *tval set to "shadow stack fault (code=3)".

The `ssload` instruction can be used to load a return address from the shadow
stack into a link register.

The `ssincp` instruction adds `XLEN/8` to the `ssp`. This instruction may be
used to remove a shadow stack frame from the shadow stack.

While any register may be used as link register, conventionally the `x1` or `x5`
registers are used. The shadow stack instructions are designed to be most
efficient when the `x1` and `x5` registers are used as the link register.

[NOTE]
====
Return-address prediction stacks are a common feature of high-performance
instruction-fetch units, but they require accurate detection of instructions
used for procedure calls and returns to be effective. For RISC-V, hints as to
the instructions usage are encoded implicitly via the register numbers used.
The return-address stack (RAS) actions to pop and/or push onto the RAS are
specified in Table 2.1 of the Unprivileged specification cite:[UNPRIV].

Using `x1` or `x5` as the link register allows a program to benefit from the
return-address prediction stacks. Additionally, since the shadow stack
instructions are designed around the use of `x1` or `x5` as the link register,
using any other register as a link register would incur the cost of additional
register movements.

Compilers when generating code with backward-edge CFI must protect the link
register, e.g. `x1` and/or `x5`, from arbitrary modification by not emitting
unsafe code sequences.
====

[NOTE]
====
Programs that use the shadow stack can operate in two modes: a shadow stack mode
or a control stack mode.

In shadow stack mode, programs store the return addresses on both the regular
stack and the shadow stack in the function prologue, and then pop them them from
both stacks and compare the values before returning from the function. In the
control stack mode, programs only store the return addresses on the shadow stack
and pop it from there to return from the function.

Operating in shadow stack mode preserves the call stack layout and the ABI,
while also allowing for the detection of corruption of the return address on
the regular stack. Such programs are portable between implementations that
support the Zicfiss extension as well as those that do not. Most programs are
expected to use this mode.

Operating in control stack mode breaks the ABI, but has the benefit of avoiding
additional instructions to store the return address to two stacks, and to pop
and compare them before returning from a function. This mode also allows the
program to have a smaller regular stack as the space to save the return address
is not needed. However, such programs are not portable to implementations that
do not support the Zicfiss extension. Some just-in-time (JIT) compiled
programs may dynamically switch between using only the regular stack or only the
shadow stack to store return addresses, depending on the capabilities of the
implementation.

The prologue and epilogue of a non-leaf function in shadow stack mode is as
follows:

[listing]
    function_entry:
        addi sp,sp,-8  # push link register x1
        sd x1,(sp)     # on data stack
        #
        # Let the contents of ssp register be 0x0000000121679F8 and
        # XLEN be 64 ssp register holds the address of the top of
        # shadow stack. Let the contents of the link register x1
        # be 0x0000000010252000
        #
        # 0x00000000121679E8:[                  ]
        # 0x00000000121679F0:[                  ]
        # 0x00000000121679F8:[0xrrrrrrrrrrrrrrrr] <- ssp
        #
        sspush x1      # push link register x1 on shadow stack
        #
        # sspush store the source register value to address
        # (ssp - XLEN/8) and updates ssp to (ssp - XLEN/8) - does
        # a push. Following completion of # sspush the ssp value is
        # the new top of stack i.e. 0x0000000121679F0 and the value
        # in x1 is stored at this location
        #
        # 0x00000000121679E8:[                  ]
        # 0x00000000121679F0:[0x0000000010252000] <- ssp
        # 0x00000000121679F8:[0xrrrrrrrrrrrrrrrr]
        #
         :
         :
        ld x1,(sp)     # pop link register x1 from data stack
        addi sp,sp,8
        sspopchk x1    # compare link register x1 to shadow
                       # return address; faults if not same
        #
        # sspopchk loads the value from location addressed by ssp and
        # compares the loaded value to the value held in the register
        # source and if the two are identical updates ssp to
        # (ssp + XLEN/8) - does a pop and a check. Following
        # completion of sspopchk the ssp value is the # new top of
        # stack i.e. 0x00000000121679F8
        #
        # 0x00000000121679E8:[                  ]
        # 0x00000000121679F0:[0x0000000010252000]
        # 0x00000000121679F8:[0xrrrrrrrrrrrrrrrr] <- ssp
        #
        ret

The prologue and epilogue of a non-leaf function when operating in control stack
mode is as follows:

[listing]
    function_entry:
        #
        # Let the contents of ssp register be 0x19740428 and XLEN be 32
        # ssp register holds the address of the top of shadow stack
        # Let the contents of the link register x1 be 0x19791216
        #
        # 0x19740418:[          ]
        # 0x19740420:[          ]
        # 0x19740428:[0xrrrrrrrr] <- ssp
        #
        sspush x1      # push link register x1 on shadow stack
        #
        # Following sspush the shadow stack and ssp are as follows:
        #
        # 0x19740418:[          ]
        # 0x19740420:[0x19791216] <- ssp
        # 0x19740428:[0xrrrrrrrr]
        #
         :
         :
        ssload x1      # load return address from shadow stack
        ssincp         # increment ssp by (XLEN/8)
        #
        # ssload loads the value from location addressed by ssp into
        # destination register. ssincp updates ssp to (ssp + XLEN/8)
        # - does a pop. Following completion of ssincp the ssp value
        # is the new top of stack i.e. 0x19740428
        #
        # 0x19740418:[          ]
        # 0x19740420:[0x19791216]
        # 0x19740428:[0xrrrrrrrr] <- ssp
        #
        ret

These examples illustrate the use of `x1` register as the link register.
Alternatively, the `x5` register may also be used as the link register.

A leaf function (i.e., a function that does not itself make function calls) does
not need to push the link register to the shadow stack or pop it from the shadow
stack in either shadow stack mode or in control stack mode. The return value may
be held in the link register itself for the duration of the leaf function
execution.
====

The `ssload`, `c.sspopchk`, and `sspopchk` instructions perform a load
identically to the existing `LOAD` instruction, with the difference that the
base is implicitly `ssp` and the width is implicitly `XLEN`.

The `sspush` and `c.sspush` instructions performs a store identically to the
existing `STORE` instruction, with the difference that the base is implicitly
`ssp` and the width is implicitly `XLEN`.

The `sspush`, `c.sspush`, `sspopchk`, `c.sspopchk`, and `ssload` require the
virtual address in `ssp` to have a shadow stack attribute (see <<SSMP>>).

Correct execution of `sspush`, `c.sspush`, `sspopchk`, `c.sspopchk`, and `ssload`
require that `ssp` refers to idempotent memory. If the memory reference by
`ssp` is not idempotent, then the `sspush`/`c.sspush` instructions cause a
store/AMO access-fault exception, and the `ssload`/`sspopchk`/`c.sspopchk`
instructions cause a load access-fault exception.

If the virtual address in `ssp` is not `XLEN` aligned, then the `ssload`/
`sspopchk`/`c.sspopchk` instructions cause a load access-fault exception, and
the `sspush`/`c.sspush` instructions cause a store/AMO access-fault exception.

[NOTE]
====
Misaligned accesses to shadow stack are not required and enforcing alignment is
more secure to detect errors in the program. An access-fault exception is raised
instead of address-misaligned exception in such cases to indicate fatality and
that the instruction must not be emulated by a trap handler.

The `sspopchk` instruction performs a load followed by a check of the loaded
data value with the link register source. If the check against the link register
faults, and the instruction is restarted by the trap handler, then the instruction
will perform a load again. If the memory from which the load is performed is
non-idempotent, then the second load may cause unexpected side effects.
Instructions that load from the shadow stack require the memory referenced by
`ssp` to be idempotent to avoid such concerns. Locating shadow stacks in
non-idempotent memory, such as non-idempotent device memory, is not an expected
usage, and requiring memory referenced by `ssp` to be idempotent does not pose a
significant restriction.
====

The operation of the `sspush` and `c.sspush` instructions is as follows:

.`sspush` and `c.sspush` operation
[listing]
----
If (xSSE == 1)
    mem[ssp - (XLEN/8)] = X(src)  # Store src value to ssp - XLEN/8
    ssp = ssp - (XLEN/8)          # decrement ssp by XLEN/8
endif
----

The operation of the `ssload` instruction is as follows:

.`ssload` operation
[listing]
----
if (xSSE == 1)
    X(dst) = mem[ssp]          # Load dst from address in ssp
                               # Only x1 and x5 may be used as dst
else
    X(dst) = 0
endif
----

The operation of the `ssincp` and `c.ssincp` instructions is as follows:

.`ssincp` and `c.ssincp` operation
[listing]
----
if (xSSE == 1)
    ssp = ssp + XLEN/8
endif
----

The operation of the `sspopchk` and `c.sspopchk` instructions is as follows:

.`sspopchk` and `c.sspopchk` operation
[listing]
----
if (xSSE == 1)
    temp = mem[ssp]            # Load temp from address in ssp and
    if temp != X(src)          # Compare temp to value in src and
                               # cause an integrity-fault exception
                               # if they are not bitwise equal.
                               # Only x1 and x5 may be used as src
       Raise integrity-fault exception
    else
       ssp = ssp + (XLEN/8)    # increment ssp by XLEN/8.
    endif
endif
----

The `ssp` is incremented by `sspopchk` and `c.sspopchk` only if the load from
the shadow stack completes successfully. The `ssp` is decremented by `sspush`
and `c.sspush` only if the store to the shadow stack completes successfully.

[NOTE]
====
The use of the compressed instruction `c.sspush x1` to push on the shadow stack
is most efficient when the ABI uses `x1` as the link register, as the link
register may then be pushed without needing a register-to-register move in the
function prologue. To use the compressed instruction `c.sspopchk x5`, the
function should pop the return address from regular stack into the alternate
link register `x5` and use the `c.sspopchk x5` to compare the return address to
the shadow copy stored on the shadow stack. The function then uses `c.jr x5` to
jump to the return address.

[listing]
----
    function_entry:
        c.addi sp,sp,-8  # push link register x1
        c.sd x1,(sp)     # on data stack
        c.sspush x1      # push link register x1 on shadow stack
         :
         :
        c.ld x5,(sp)     # pop link register x5 from data stack
        c.addi sp,sp,8
        c.sspopchk x5    # compare link register x5 to shadow
                         # return address; faults if not same
        c.jr x5
----

====

[NOTE]
====
Store-to-load forwarding is a common technique employed by high-performance
processor implementations. Zicfiss implementations may prevent forwarding from
a non-shadow-stack store to `ssload`/`sspopchk`/`c.sspopchk` instructions. A
non-shadow-stack store causes a fault if done to a page mapped as a shadow
stack. However, such determination may be delayed till the PTE has been examined
and thus may be used to transiently forward the data from such stores to a
`ssload`/`sspopchk`/`c.sspopchk`.
====

[NOTE]
====
A common operation performed on stacks is to unwind them to support constructs
like `setjmp`/`longjmp`, C++ exception handling, etc. A program that uses shadow
stacks must unwind the shadow stack in addition to the stack used to store data.
The unwind function must verify that it does not accidentally unwind past the
bounds of the shadow stack. Shadow stacks are expected to be bounded on each end
using guard pages, i.e. pages that do not have a shadow stack attribute. To
detect if the unwind occurs past the bounds of the shadow stack, the unwind may
be done in maximal increments of 4 KiB and testing for the `ssp` to be still
pointing to a shadow stack page or has unwound into the guard page. The
following examples illustrate the use of shadow stack instructions to
unwind a shadow stack. This example assumes that the `setjmp` function itself does
not push on to the shadow stack (being a leaf function, it is not required to).

[listing]
setjmp() {
    :
    :
    // read and save the shadow stack pointer to jmp_buf
    asm("ssprr %0" : "=r"(cur_ssp):);
    jmp_buf->saved_ssp = cur_ssp;
    :
    :
}
longjmp() {
    :
    // Read current shadow stack pointer and
    // compute number of call frames to unwind
    asm("ssprr %0" : "=r"(cur_ssp):);
    // Skip the unwind if backward-edge CFI not enabled
    asm("beqz %0, back_cfi_not_enabled" : "=r"(cur_ssp):);
    // Unwind the frames in a loop
    while ( jmp_buf->saved_ssp > cur_ssp ) {
        // advance by a maximum of 4K at a time to avoid
        // unwinding past bounds of the shadow stack
        cur_ssp = ( (jmp_buf->saved_ssp - cur_ssp) >= 4096 ) ?
                  (cur_ssp + 4096) : jmp_buf->saved_ssp;
        asm("csrw ssp, %0" : :  "r" (cur_ssp));
        // Test if unwound past the shadow stack bounds
        asm("ssload x5");
    }
back_cfi_not_enabled:
    :
}
====

[[SSP_READ]]
=== Read `ssp` into a register

The `ssprr` instruction is provided to move the contents of `ssp` to a destination
register.

[wavedrom, ,svg]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:['dst']},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  5, name: '00000'},
  {bits: 12, name: '100000011101', attr:['ssprr']},
], config:{lanes: 1, hspace:1024}}
....

Encoding `rd` as `x0` is not supported for `ssprr`.

The operation of the `ssprr` instructions is as follows:

.`ssprr` operation
[listing]
----
If (xSSE == 1)
    X(dst) = ssp
else
    X(dst) = 0
endif
----

[NOTE]
====
The property of Zimop writing 0 to the `rd` when the extension using Zimop is
not implemented, enabled for use, or not enabled may be used by to determine if
Zicfiss extension is enabled. For example, functions that unwind shadow stacks
may skip over the unwind actions by dynamically detecting if the Zicfiss
extension is enabled.

An example sequence such as the following may be used:

[listing]
    ssprr t0                  # mv ssp to t0
    beqz zicfiss_not_enabled  # zero is not a valid shadow stack
                              # pointer by convention
    # Zicfiss is enabled
    :
    :
zicfiss_not_active:

Operating systems and runtimes must not locate shadow stacks at address 0 to
assist with the use of such code sequences.
====

[[SS_SWAP]]
=== Atomic Swap from a shadow stack location

The `ssamoswap` instruction performs an atomic swap operation between the `XLEN`
bits of the `src` register and the `XLEN` bits located on the shadow stack at the
address specified in the `addr` register. The resulting value from the swap
operation is then stored into the register specified in the `dst` operand.

[wavedrom, ,svg]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'SYSTEM'},
  {bits:  5, name: 'rd', attr:['dst']},
  {bits:  3, name: 'funct3', attr:['100']},
  {bits:  5, name: 'rs1', attr:['addr']},
  {bits:  5, name: 'rs2', attr:['src']},
  {bits:  7, name: '1000001', attr:['ssamoswap']},
], config:{lanes: 1, hspace:1024}}
....

Encoding `rd` as `x0` is not supported for `ssamoswap`.

The `ssamoswap` is always sequentially consistent and cannot be reordered with
earlier or later memory operations from the same hart.

The `ssamoswap` causes a store/AMO access-fault exception if the address in
`addr` does not have a shadow stack attribute (see <<SSMP>>), of if the address
 is not `XLEN` aligned, or if the memory reference by `ssp` is not idempotent.

The operation of the `ssamoswap` instructions is as follows:

.`ssamoswap` operation
[listing]
----
If (xSSE == 1)
    Perform the following atomically with sequential consistency
        X(dst) = mem[X(addr)]
        mem[X(addr)] = X(src)
else
    X(dst) = 0
endif
----

[NOTE]
====
Stack switching is a common operation in user programs as well as supervisor
programs. When a stack switch is performed the stack pointer of the currently
active stack is saved into a context data structure and the new stack is made
active by loading a new stack pointer from a context data structure.

When shadow stacks are active for a program, the program needs to additionally
switch the shadow stack pointer. If the pointer to the top of the deactivated
shadow stack is held in a context data structure, then it  may be susceptible to
memory corruption vulnerabilities. To protect the pointer value, the program may
store it at the top of the deactivated shadow stack itself and thereby create a
checkpoint.

An example sequence to store and restore the shadow stack pointer is as follows:

[listing]
# The a0 register holds the pointer to top of new shadow
# to switch to. The current ssp is first pushed on the current
# shadow stack and the ssp is restored from new shadow stack
save_shadow_stack_pointer:
    ssprr  x5                   # read ssp and push value onto
    sspush x5                   # shadow stack. The [ssp] now
    addi   x5, x5, -(XLEN/8)    # holds ptr+XLEN/8. The [x5] now
                                # holds ptr. Save away x5
                                # into a context structure to
                                # restore later.
restore_shadow_stack_pointer:
    ssamoswap t0, x0, (a0)      # t0=*[a0] and *[a0]=0
                                # The [a0] should hold ptr
                                # The [t0] should hold ptr+XLEN/8
    addi   a0, a0, (XLEN/8)     # a0+XLEN/8 must match to t0
    bne    t0, a0, crash        # if not crash program
    csrw   ssp, t0              # setup new ssp

Further, the program may enforce an invariant that a shadow stack can be active
only on one hart by using the `ssamoswap` when performing the restore from the
checkpoint such that the checkpoint data is zeroed as part of the restore
sequence. If multiple hart attempt to restore the checkpoint data, only one
of them succeeds.
====

[[SSMP]]
=== Shadow Stack Memory Protection

To protect shadow stack memory the memory is associated with a new page type -
Shadow Stack (SS) page - in the page tables.

When the `Smepmp` extension is supported the PMP configuration registers are
enhanced to support a shadow stack memory region for use by M-mode.

==== Virtual-Memory system extension for Shadow Stack

The shadow stack memory is protected using page table attributes such that it
cannot be stored to by instructions other than `sspush`, `c.sspush`, and
`ssamoswap`. The `ssload`, `sspopchk`, and `c.sspopchk` instructions can only
load from shadow stack memory.

The `sspush` and `c.sspush` instructions perform a store. The `ssamoswap`
instruction performs an AMO. The `ssload`, `sspopchk`, and `c.sspopchk`
instructions perfom a load.

The shadow stack can be read using all instructions that load from memory.

Attempting to fetch an instruction from a shadow stack page raises an
instruction page-fault exception.

The encoding `R=0`, `W=1`, and `X=0`, is defined to represent a shadow stack
page.  When `menvcfg.SSE=0`, this encoding remains reserved. When `V=1` and
`henvcfg.SSE=0`, this encoding remains reserved at `VS` and `VU`.

The following faults may occur:

. If the accessed page is a shadow stack page:
.. Stores other than `sspush` and `ssamoswap` cause store/AMO access-fault.
.. Instruction fetches cause an instruction page-fault.
. If the accessed page is not a shadow stack page or if the page is in
  non-idempotent memory:
.. `ssamoswap`, `c.sspush`, and `sspush` cause a store/AMO access-fault.
.. `ssload`, `c.sspopchk`, and `sspopchk` cause a load access-fault.

[NOTE]
====
Stores to shadow stack by instructions other than `sspush`, `c.sspush`, and
`ssamoswap` cause a store/AMO access-fault exception, rather than a store/AMO
page-fault exception, to indicate fatality.

If a store/AMO page-fault was triggered, it would suggest that the operating
system should service that fault and correct the condition. Correcting the
condition is not possible in this case. The page-fault handler would have to
resort to decoding the opcode of the instruction that caused the page-fault to
determine if it was caused by non-shadow-stack-stores to shadow stack pages
(which is a fatal condition) vs. a page fault caused by an `sspush`, `c.sspush`,
or `ssamoswap` to a non-resident page (which is a recoverable condition). Since
the operating system page-fault handler is typically performance-critical,
causing an access-fault instead of a page-fault enables the operating system to
easily distinguish between the fatal/non-recoverable conditions and recoverable
page-faults.

On implementations where address-misaligned exception is prioritized higher than
access-fault exception, a trap handler handler that emulates misaligned stores
must cause an access-fault exception if the store is not `sspush`, `c.sspush`,
or, `ssamoswap`, and the store is being made to a shadow stack page.

Shadow stack instructions cause an access-fault if the accessed page is not a
shadow stack page or if the page is in non-idempotent memory to similarly
indicate fatality.

Instruction fetch from a shadow stack page causes a page-fault because this
condition is clearly distinguished by a unique cause code and is non-recoverable.
====

To support these rules, the virtual address translation process specified in
section 4.3.2 of the Privileged Specification cite:[PRIV] is modified as
follows:
[start=3]
3. If `pte.v = 0` or if any bits of encodings that are reserved for future
   standard use are set within `pte`, stop and raise a page-fault exception
   corresponding to the original access type. The encoding `pte.xwr = 010b`
   is not reserved if `V=0` and `menvcfg.SSE` is 1 or if `V=1` and
   `henvcfg.SSE` is 1.

4. Otherwise, the PTE is valid. If `pte.r = 1` or `pte.w = 1` or `pte.x = 1`,
   go to step 5. Otherwise, this PTE is a pointer to the next level of the page
   table. Let `i = i - 1`. If `i < 0`, store and raise a page-fault exception
   corresponding to the original access type. Otherwise, let `a = pte.ppn x
   PAGESIZE` and go to step 2.

5. A leaf PTE has been found. If the memory access is by a shadow stack
   instruction and `pte.xwr != 010b`, then cause an access-violation exception
   corresponding to the access type. If the memory access is a store/AMO and
   `pte.xwr == 010b`, then cause a store/AMO access-violation. If the requested
   memory access is not allowed by the `pte.r`, `pte.w`, `pte.x`, and `pte.u`
   bits, given the current privilege mode and the value of the `SUM` and `MXR`
   fields of the `mstatus` register, stop and raise a page-fault exception
   corresponding to the original access type.

The PMA checks are extended to require memory referenced by `sspush`, `ssload`,
`ssamoswap`, `c.sspush`, `c.sspopchk`, and `sspopchk` to be idempotent.

The `U` and `SUM` bit enforcement is performed normally for shadow stack
instruction initiated memory accesses. The state of the `MXR` bit does not
affect read access to a shadow stack page as the shadow stack page is always
readable by all instructions that load from memory.

Svpbmt and Svnapot extensions are supported for shadow stack pages.

[NOTE]
====
All instructions that load from memory are allowed to read the shadow stack. The
shadow stack only holds a copy of the link register as saved on the regular
stack. The ability to read the shadow stack is useful for debugging, performance
profiling, and other use cases.

Operating systems should protect against writable non-shadow-stack alias
virtual-addresses mappings being created to the physical memory of the
shadow stack.

Shadow stacks are expected to be bounded on each end using guard pages, so that
no two shadow stacks are adjacent to each other. This guards against accidentally
underflowing or overflowing from one shadow stack to another. Traditionally,
a guard page for a stack is a page that is inaccessible to the process owning
the stack. For shadow stacks, the guard page may also be a non-shadow-stack
page that is otherwise accessible to the process owning the shadow stack
because shadow stack loads and stores to non-shadow-stack pages cause an
access-fault exception.
====

The G-stage address translation and protections remain unaffected by Zicfiss
extension. When G-stage page tables are active, the `ssamoswap`, `ssload`,
`c.sspopchk`, and `sspopchk` instructions require the G-stage page table to have
read permission for the accessed memory, whereas the `ssamoswap`, `c.sspush`, and
`sspush` instructions require write permission. The `xwr == 010b` encoding in
the G-stage PTE remains reserved.

[NOTE]
====
A future extension may define a shadow stack encoding in the G-stage page table
to support use cases such as a hypervisor enforcing shadow stack protections for
its guests.
====

[[PMP_SS]]
==== PMP extension for shadow stack

When privilege mode is less than M, the PMP region accessed by `sspush`,
`c.sspush`, and `ssamoswap` must provide write permission and the PMP region
accessed by `ssload`, `c.sspopchk`, and `sspopchk` must provide read permission.

The M-mode memory accesses by `sspush`, `c.sspush` and `ssamoswap` instructions
test for write permission in the matching PMP entry when permission checking is
required.

The M-mode memory accesses by `ssload`, `c.sspopchk`, and `sspopchk` instructions
test for read permission in the matching PMP entry when permission checking is
required.

A new WARL field `SSPMP` is defined in the `mseccfg` CSR to identify a PMP entry
as the shadow stack memory region for M-mode accesses.

When `mseccfg.MML` is 1, the `SSPMP` field is read-only else it may be written.

When the `SSPMP` field is not zero, the following rules are additionally
enforced for M-mode memory accesses:

* `sspush`, `c.sspush`, `ssload`, `sspopchk`, `c.sspopchk`, and `ssamoswap`
  instructions must match the PMP entry identified by `SSPMP` else an
  access-fault exception corresponding to the access type occurs.

* Write by instructions other than `sspush`, `c.sspush`, and `ssamoswap` that
  match the PMP entry identified by `SSPMP` cause an store/AMO
  access-fault exception.

[NOTE]
====
The PMP region used for the M-mode shadow stack is expected to be made
inaccessible for U-mode and S-mode read and write accesses. Allowing write
access violates the integrity of the shadow stack, and allowing read access may
lead to disclosure of M-mode return addresses.
====
