[[intro]]
== Introduction

The Zicfiss extension provides Control-flow Integrity (CFI) capabilities to
defend against Return-Oriented Programming (ROP) and the Zicfilp extension
provides CFI capabilities to defend against Call/Jump-Oriented Programming
(COP/JOP) style control-flow subversion attacks. These attack methodologies use
code sequences in authorized modules, with at least one instruction in the
sequence being a control transfer instruction that depends on attacker-controlled
data either in the return stack or in memory used to obtain the target address
for a call or jump. Attackers stitch these sequences together by diverting the
control flow instructions (e.g., `JALR`, `C.JR`, `C.JALR`), from their original
target address to a new target via modification in the return stack or in the
memory used to obtain the jump/call target address.

RV32/RV64 provide two types of control transfer instructions - unconditional
jumps and conditional branches. Conditional branches encode an offset in the
immediate field of the instruction and are thus direct branches that are not
susceptible to control-flow subversion.

Unconditional direct jumps using `JAL` transfer control to a target that is in a
+/- 1 MiB range from the current `pc`. Unconditional indirect jumps using the
`JALR` obtain their branch target by adding the sign extended 12-bit immediate
encoded in the instruction to the `rs1` register.

The RV32I/RV64I does not have a dedicated instruction for calling a procedure or
returning from a procedure. A `JAL` or `JALR` may be used to perform a procedure
call and `JALR` to return from a procedure. The RISC-V ABI however defines the
convention that a `JAL`/`JALR` where `rd` (i.e. the link register) is `x1` or
`x5` is a procedure call, and a `JALR` where `rs1` is the conventional
link register (i.e. `x1` or `x5`) is a return from procedure. The architecture
allows for using these hints and conventions to support return address
prediction. The hints are specified in Table 2.1 of the Unprivileged ISA
specifications cite:[UNPRIV].

The RVC standard extension for compressed instructions provides unconditional
jump and conditional branch instructions. The `C.J` and `C.JAL` instructions
encode an offset in the immediate field of the instruction and thus are not
susceptible to control-flow subversion.

The `C.JR` and `C.JALR` RVC instruction performs an unconditional control
transfer to the address in register `rs1`. The `C.JALR` additionally writes the
address of the instruction following the jump (`pc+2`) to the link register `x1`
and is a procedure call. The `C.JR` is a return from procedure if `rs1` is a
conventional link register (i.e. `x1` or `x5`); else it is an indirect jump.

The term _call_ is used to refer to a `JAL` or `JALR` instruction with a link
register as destination, i.e., `rd != x0`. Conventionally, the link register is
`x1` or `x5`. A _call_ using `JAL` or `C.JAL` is termed a direct call. A
`C.JALR` expands to `JALR x1, 0(rs1)` and is a _call_. A _call_ using `JALR` or
`C.JALR` is termed an _indirect-call_.

The term _return_ is used to refer to a `JALR` instruction with `rd == x0` and
with `rs1 == x1` or `rs1 == x5` and `rd == x0`. A `C.JR` instruction expands to
`JALR x0, 0(rs1)` and is a _return_ if `rs1 == x1` or `rs1 == x5`.

The term _indirect-jump_ is used to refer to a `JALR` instruction with `rd == x0`
and where the `rs1` is not `x1` or `x5` (i.e., not a return). A `C.JR`
instruction where `rs1` is not `x1` or `x5` (i.e., not a return) is an
_indirect-jump_.

The Zicfiss and Zicfilp extensions build on these conventions and hints.

=== Backward-edge control-flow integrity

To enforce backward-edge control-flow integrity, the Zicfiss extension
introduces a shadow stack.

The shadow stack is designed to provide integrity to control transfers performed
using a _return_ (where the return may be from a procedure invoked using an
indirect call or a direct call), and this is referred to as backward-edge
protection.

A program using backward-edge control-flow integrity has two stacks: a regular
stack and a shadow stack. The shadow stack is used to spill the link register,
if required, by non-leaf functions. An additional register, shadow-stack-pointer
(`ssp`), is introduced in the architecture to hold the address of the top of the
active shadow stack.

The shadow stack is architecturally protected from inadvertent corruptions and
modifications, as detailed later (See <<SSMP>>).

The Zicfiss extension provides instructions to store and load the link register
to/from the shadow stack and to check the integrity of the return address. The
extension provides instructions to support common stack maintenance operations
such as stack unwinding and stack switching.

The Zicfiss instructions are encoded using a subset of "May be op" instructions
defined by the Zimop and Zcmop extensions. This subset of instructions revert to
their Zimop/Zcmop defined behavior when the Zicfiss extension is not implemented
or if the extension has not been activated at a privilege mode. A program that
is built with Zicfiss instructions can thus continue to operate correctly, but
without backward-edge control-flow integrity, on processors that do not support
the Zicfiss extension or if the Zicfiss extension is not active.

The Zicfiss extensions may be activated for use individually and independently
for each privilege mode.

Compilers should flag each object file (for example, using flags in the elf
attributes) to indicate if the object file has been compiled with the Zicfiss
instructions. The linker should flag (for example, using flags in the elf
attributes) the binary/executable generated by linking objects as being
compiled with the Zicfiss instructions only if all the object files that are
linked have the same Zicfiss attributes.

The dynamic loader should activate the use of Zicfiss extension for an
application only if all executables (the application and the dependent
dynamically linked libraries) used by that application use the Zicfiss
extension.

An application that has the Zicfiss extension active may request the dynamic
loader at runtime to load a new dynamic shared object (using dlopen() for
example). If the requested object does not have the Zicfiss attribute then
the dynamic loader, based on its policy (e.g, established by the operating
system or the administrator) configuration, either fail the request or
deactivate the Zicfiss extension for the application.

When the Zicfiss extension is not active or not implemented, the Zicfiss
instructions revert to their Zimop/Zcmop defined behavior. This allows a
compiled with Zicfiss instructions to operate correctly but without
backward-edge control-flow integrity.

The Zicfiss extension is specified in <<backward>> and the CSR state introduced
is specified in <<CSRs>>. The Zicfiss extension depends on the Zicsr, A, Zimop,
and Zcmop extensions.

=== Forward-edge control-flow integrity

To enforce forward edge control-flow integrity, Zicfilp extension introduces
a landing pad (`lpad`) instruction that allows software to indicate valid
targets for indirect calls and jumps in a program.

Compilers emit a landing pad instruction as the first instruction of an
address-taken functions, as well as at any indirect jump targets. A landing pad
instruction is not required in functions that are only reached using a direct
call or direct jump.

The landing pad is designed to provide integrity to control transfers performed
using indirect call and jumps, and this is referred to as forward-edge
protection. When the Zicfilp is active, the hart tracks an expected landing pad
(`ELP`) state that is updated by an _indirect_call_ or _indirect_jump_ to
require a landing pad instruction at the target of the branch. If the
instruction at the target is not a landing pad, then an integrity-fault
exception is raised.

A landing pad may be optionally associated with a 20-bit label. With labeling
enabled, the number of landing pads that can be reached from an indirect call
or jump site can be defined using programming language-based policies. Labeling
of the landing pads enables software to achieve greater precision in pairing up
indirect call/jump sites with valid targets. When labeling of landing pads
is used, indirect call or indirect jump site can specify the expected label of
the landing pad and thereby constrain the set of landing pads that may be
reached from each indirect call or indirect jump site in the program.

In the simplest form, a program can be built with a single label value to
implement a coarse-grained version of forward-edge control-flow integrity. By
constraining gadgets to be preceded by a landing pad instruction that marks
the start of indirect callable functions, the program can significantly reduce
the available gadget space. A second form of label generation may generate a
signature, such as a MAC, using the prototype of the function. Programs that use
this approach would further constrain the gadgets accessible from a call site to
only indirect callable functions that match the prototype of the called
functions. Another approach to label generation involves analyzing the
control-flow-graph (CFG) of the program, which can lead to even more stringent
constraints on the set of reachable gadgets. Such programs may further use
multiple labels per function, which means that if a function is called from two
or more call sites, the functions can be labeled as reachable from each of the
call sites. For instance, consider two call sites A and B, where A calls the
functions X and Y, and B calls the functions Y and Z. In a single label scheme,
functions X, Y, and Z would need to be assigned the same label so that both call
sites A and B can invoke the common function Y. This scheme would allow call
site A to also call function Z and call site B to also call function X. However,
if function Y was assigned two labels - one corresponding to call site A and the
other to call site B, then Y can be invoked by both call sites, but X can only be
invoked by call site A and Z can only be invoked by call site B. To support
multiple labels, the compiler could generate a call-site-specific entry point
for shared functions, with each entry point having its own landing pad
instruction followed by a direct branch to the start of the function. This would
allow the function to be labeled with multiple labels, each corresponding to a
specific call site. A portion of the label space may be dedicated to labeled
landing pads that are only valid targets of an indirect jump (and not an
indirect call).

The `lpad` instruction uses the code points defined as HINTs for the `AUIPC`
opcode. When Zicfilp is not active at a privilege level or when the extension
is not implemented, the landing pad instruction executes as a no-op. A program
that is built with `lpad` instruction can thus continue to operate correctly,
but without forward-edge control-flow integrity, on processors that do not
support the Zicfilp extension or if the Zicfilp extension is not active.

As discussed earlier for the Zicfiss extension, compilers, linkers, and dynamic
loaders should provided an attribute flag to indicate if the program has been
compiled with the Zicfilp extension and use that to determine if the Zicfilp
extension should be activated.

When Zicfilp extension is not active or not implemented, that hart does not
required landing pad instructions at targets of indirect calls/jumps and the
landing instructions revert to being a no-op. This allows a program compiled
with landing pad instructions to operate correctly but without forward-edge
control-flow integrity.

The Zicfilp extensions may be activated for use individually and independently
for each privilege mode.

The Zicfilp extension is specified in <<forward>> and the CSR state introduced
is specified in <<CSRs>>. The Zicfilp extension depends on the Zicsr extension.
