[[forward]]
== Landing pad (Zicfilp)

To enforce forward-edge control-flow integrity, the Zicfilp extension introduces
a landing pad (`lpad`) instruction. The `lpad` instruction that must be placed
at the program locations that are valid targets of indirect jumps or calls. The
`lpad` instruction (See <<LP_INST>>) is encoded using the `AUIPC` major opcode
with `rd=x0`.

To enforce that the target of an indirect call or indirect jump must be a valid
landing pad instruction, the hart maintains an expected landing pad (`ELP`) state
to determine if a landing pad instruction is required at the target of an
indirect call or an indirect jump. The `ELP` state can be one of:

* 0 - `NO_LP_EXPECTED`
* 1 - `LP_EXPECTED`

The `ELP` state is initialized to `NO_LP_EXPECTED` by the hardware upon reset.

The Zicfilp extension, when active, determines if an indirect call or an
indirect jump must land on a landing pad, as specified in <<IND_CALL_JMP>>. If
`is_lp_expected` is 1, then the hart updates the `ELP` to `LP_EXPECTED`.

[[IND_CALL_JMP]]
.Landing pad expected determination
[listing]
----
  is_lp_expected = ( (JALR || C.JR || C.JALR) &&
                     (rs1 != x1) && (rs1 != x5) && (rs1 != x7) ) ? 1 : 0;
----

An indirect branch using `JALR`, `C.JALR`, or `C.JR` with `rs1` as `x7` is
termed a software guarded branch. Such branches do not need to land on a
`lpad` instruction and thus do not set `ELP` to `LP_EXPECTED`.

[NOTE]
====
When the register source is a link register and the register destination is `x0`
then its a return from a procedure and does not require a landing pad at the
target.

When the register source and register destination are both link registers then
its a semantically-direct-call. For example, the `call offset` pseudoinstruction
may expand to a two instruction sequence composed of a `lui ra, imm20` or a
`auipc ra, imm20` instruction followed by a `jalr ra, imm12(ra)` instruction
where `ra` is the link register (either `x1` or `x5`). Since the address of the
procedure was not explicitly taken and the computed address is not obtained from
mutable memory, such semantically-direct calls do not require a landing pad to
be placed at the target. Compilers and JITers must only use the
semantically-direct calls only if when the `rs1` was computed as a PC-relative
or an absolute offset to the symbol.

The `tail offset` pseudoinstruction used to tail call a far-away procedure may
also be expanded to a two instruction sequence composed of a `lui x7, imm20` or
`auipc x7, imm20` followed by a `jalr x0, x7`. Since the address of the
procedure was not explicitly taken and the computed address is not obtained from
mutable memory, such semantically-direct tail-calls do not require a landing pad
to be placed at the target.

Software guarded branches may also be used by compilers to generate code for
constructs like switch-cases. When using the software guarded branches, the
compiler is required to ensure it has full control on the possible jump
targets (e.g., by obtaining the targets from a read-only table in memory and
performing bounds checking on the index into the table, etc.).
====

The landing pad may be labeled. Zicfilp extension designates the register `x7`
for use as the landing pad label register. To support labeled landing pads, the
indirect call/jump sites establish an expected landing pad label (e.g., using
the `lui` instruction) in the bits 31:12 of the `x7` register. The `lpad`
instruction is encoded with a 20-bit immediate value called the landing-pad-label
(`LPL`) that is matched to the expected landing pad label. When `LPL` is encoded
as zero, the `lpad` instruction does not perform the label check and in programs
built with this single label mode of operation the indirect call/jump sites do
not need to establish an expected landing pad label value in `x7`.

When `ELP` is set to `LP_EXPECTED`, if the next instruction in the instruction
stream is not 4-byte aligned, or is not `lpad`, or if the landing pad label
encoded in `lpad` is not zero and does not match the expected landing pad label
in bits 31:12 of the `x7` register, then an illegal-instruction exception is
raised else the `ELP` is updated to `NO_LP_EXPECTED`.

[NOTE]
====
The tracking of `ELP` and the requirement for a landing pad instruction
at the target of indirect call and jump enables a processor implementation to
significantly reduce or to prevent speculation to non-landing-pad instructions.
Constraining speculation using this technique, greatly reduces the gadget space
and increases the difficulty of using techniques such as branch-target-injection,
also known as Spectre variant 2, which use speculative execution to leak data
through side channels.

The `lpad` requires a 4-byte alignment to address the concatenation of two
instructions `A` and `B` accidentally forming an unintended landing pad in the
program. For example, consider a 32-bit instruction where the bytes 3 and 2 have
a pattern of `?017h` (for example, the immediate fields of a `lui`, `auipc`, or
a `jal` instruction), followed by a 16-bit or a 32-bit instruction. When
patterns that can accidentally form a valid landing pad are detected, the
assembler or linker can force instruction `A` to be aligned to a 4-byte
boundary to force the unintended `lpad` pattern to become misaligned and thus
not a valid landing pad or may use an alternate register allocation to prevent
the accidental landing pad.
====

[[FCIFIACT]]
=== Forward-edge-CFI-active state

The term `xFCFIE` is used to determine if forward-edge CFI provided by the
Zicfilp extension is active at privilege mode `x` and is defined as follows:

.`xFCFIE` determination
[listing]
----
if ( privilege == M-mode )
    xFCFIE = mseccfg.MFCFIE
else if ( privilege == S-mode )
    xFCFIE = (V == 0) ? menvcfg.SFCFIE : henvcfg.SFCFIE
else
    xFCFIE = (V == 0) ? mstatus.UFCFIE : vsstatus.UFCFIE
----

[NOTE]
====
The Zicfilp must be explicitly activated for use at each privilege mode.

Programs compiled with the `lpad` instruction continue to function correctly,
but without forward-edge CFI protection, when the Zicfilp extension is not
implemented or is not active.
====

[[LP_INST]]
=== Landing pad instruction

When Zicfilp is active, `lpad` is the only instruction allowed to execute when
the `ELP` state is `LP_EXPECTED`. If Zicfilp is not active then the instruction
is a no-op. If Zicfilp is active, the `lpad` instruction causes an
illegal-instruction exception if any of the following conditions are true:

* The `pc` is not 4-byte aligned.
* The `ELP` is `LP_EXPECTED` and the `LPL` is not zero and the `LPL` does not
  match the expected landing pad label in bits 31:12 of the `x7` register.

If the instruction causes an illegal-instruction exception, the `ELP` does not
change. The behavior of the trap caused by this illegal-instruction exception is
specified in section <<FORWARD_TRAPS>>. If an illegal-instruction exception is
not caused then the `ELP` is updated to `NO_LP_EXPECTED`.

[wavedrom, ,svg]
....
{reg: [
  {bits:  7, name: 'opcode', attr:'AUIPC'},
  {bits:  5, name: 'rd', attr:'00000'},
  {bits: 20, name: 'LPL'},
], config:{lanes: 1, hspace:1024}}
....

The operation of the `lpad` instruction is as follows:

.`lpad` operation
[listing]
----
if (xFCFIE != 0)
    // If PC not 4-byte aligned then illegal-instruction
    if pc[1:0] != 0
        Cause illegal-instruction exception
    // If landing pad label not matched -> illegal-instruction
    else if (inst.LPL != x7[31:12] && inst.LPL != 0 && ELP == LP_EXPECTED)
        Cause illegal-instruction exception
    else
        ELP = NO_LP_EXPECTED
else
    no-op
endif
----

[[FORWARD_TRAPS]]
=== Preserving expected landing pad state on traps

A trap may need to be delivered to the same or to a higher privilege mode upon
completion of `JALR`/`C.JALR`/`C.JR`, but before the instruction at the target
of indirect call/jump was decoded, due to:

* Asynchronous interrupts.
* Synchronous exceptions with priority higher than that of an illegal-instruction
  exception (See Table 3.7 of Privileged Specification cite:[PRIV]).

The illegal-instruction exception due to the instruction not being an `lpad`
instruction when `ELP` is `LP_EXPECTED` or an illegal-instruction exception
caused by the `lpad` instruction itself (See <<LP_INST>>) leads to a trap being
delivered to the same or to a higher privilege mode.

In such cases, the `ELP` prior to the trap, the previous `ELP`, must be
preserved by the trap delivery such that it can be restored on a return from the
trap. To store the previous `ELP` state on trap delivery to M-mode, a `MPELP`
bit is provided in the `mstatus` CSR. To store the previous `ELP` state on trap
delivery to S/HS-mode, a `SPELP` bit is provided in the `mstatus` CSR. The
`SPELP` bit in `mstatus` can be accessed through the `sstatus` CSR. To store
the previous `ELP` state on traps to VS-mode, a `SPELP` bit is defined in the
`vsstatus` (VS-modes version of `sstatus`).

When a trap is taken into privilege mode `x`, the `xPELP` is set to `ELP` and
`ELP` is set to `NO_LP_EXPECTED`.

An `MRET` or `SRET` instruction is used to return from a trap in M-mode or
S-mode, respectively. An `xRET` instruction sets the `ELP` to `xPELP`, and sets
`xPELP` to `NO_LP_EXPECTED`.

[NOTE]
====
The trap handler in privilege mode `x` must save the `xPELP` bit and the `x7`
register before performing an indirect call/jump. If the privilege mode `x`
can respond to interrupts, then the trap handler should also save these values
before enabling interrupts.

The trap handler in privilege mode `x` must restore the saved `xPELP` bit and
the `x7` register before executing the `xRET` instruction to return from a
trap.
====
