[[CSRs]]
== Shadow Stack and Landing Pad CSRs

This chapter specifies the CSR state of the Zicfiss and Zicfilp extensions.

=== Machine environment configuration registers (`menvcfg and menvcfgh`)

.Machine environment configuration register (`menvcfg`) for MXLEN=64
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'FIOM'},
  {bits:  3, name: 'WPRI'},
  {bits:  2, name: 'CBIE'},
  {bits:  1, name: 'CBCFE'},
  {bits:  1, name: 'CBZE'},
  {bits: 51, name: 'WPRI'},
  {bits:  1, name: 'SFCFIE'},
  {bits:  1, name: 'SBCFIE'},
  {bits:  1, name: 'HADE'},
  {bits:  1, name: 'PBMTE'},
  {bits:  1, name: 'STCE'},
], config:{lanes: 4, hspace:1024}}
....

Zicfiss extension introduces the `SBCFIE` field (bit 60) in `menvcfg`. When
`SBCFIE` field is 1, the Zicfiss extension is active in S-mode. When `SBCFIE`
field is 0, the Zicfiss extension is not active in S-mode and the following
rules apply to privilege modes less than M.

* Attempts to access the `ssp` CSR raise an illegal-instruction exception.
* The 32-bit Zicfiss instructions revert to their Zimop defined behavior.
* The 16-bit Zicfiss instructions revert to their Zcmop defined behavior.
* The `pte.xwr=010b` encoding in S-stage page tables is reserved.
* The `henvcfg.SBCFIE` and `sstatus.UBCFIE` fields are read-only zero.

Zicfilp extension introduces the `SFCFIE` field (bit 59) in `menvcfg`. When
`SFCFIE` field is 1, the Zicfilp extension is active in S-mode. When `SFCFIE`
field is 0, the Zicfilp extension is not active in S-mode and the following
rules apply to S-mode:

* The hart does not update the expected landing pad (`ELP`) state and the `ELP`
  state is always `NO_LP_EXPECTED`.
* The `lpad` instruction executes as a no-op.

=== Hypervisor environment configuration registers (`henvcfg and henvcfgh`)

.Hypervisor environment configuration register (`henvcfg`) for MXLEN=64
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'FIOM'},
  {bits:  3, name: 'WPRI'},
  {bits:  2, name: 'CBIE'},
  {bits:  1, name: 'CBCFE'},
  {bits:  1, name: 'CBZE'},
  {bits: 51, name: 'WPRI'},
  {bits:  1, name: 'SFCFIE'},
  {bits:  1, name: 'SBCFIE'},
  {bits:  1, name: 'HADE'},
  {bits:  1, name: 'PBMTE'},
  {bits:  1, name: 'STCE'},
], config:{lanes: 4, hspace:1024}}
....

Zicfiss extension introduces the `SBCFIE` field (bit 60) in `henvcfg`. When
`SBCFIE` field is 1, the Zicfiss extension is active in VS-mode. When `SBCFIE`
field is 0, the Zicfiss extension is not active in VS-mode and the following
rules apply when `V=1`.

* Attempts to access the `ssp` CSR raise an illegal-instruction exception.
* The 32-bit Zicfiss instructions revert to their Zimop defined behavior.
* The 16-bit Zicfiss instructions revert to their Zcmop defined behavior.
* The `pte.xwr=010b` encoding in VS-stage page tables is reserved.
* The `sstatus.UBCFIE` (really `vsstatus.UBCFIE`) field is read-only zero.

Zicfilp extension introduces the `SFCFIE` field (bit 59) in `henvcfg`. When
`SFCFIE` field is 1, the Zicfilp extension is active in VS-mode. When `SFCFIE`
field is 0, the Zicfilp extension is not active in VS-mode and the following
rules apply to VS-mode:

* The hart does not update the expected landing pad (`ELP`) state and the `ELP`
  state is always `NO_LP_EXPECTED`.
* The `lpad` instruction executes as a no-op.

=== Machine status registers (`mstatus`)

.Machine-mode status register (`mstatus`) for RV64
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SIE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'MIE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SPIE'},
  {bits:  1, name: 'UBE'},
  {bits:  1, name: 'MPIE'},
  {bits:  1, name: 'SPP'},
  {bits:  2, name: 'VS[1:0]'},
  {bits:  2, name: 'MPP[1:0]'},
  {bits:  2, name: 'FS[1:0]'},
  {bits:  2, name: 'XS[1:0]'},
  {bits:  1, name: 'MPRV'},
  {bits:  1, name: 'SUM'},
  {bits:  1, name: 'MXR'},
  {bits:  1, name: 'TVM'},
  {bits:  1, name: 'TW'},
  {bits:  1, name: 'TSR'},
  {bits:  1, name: 'UFCFIE'},
  {bits:  1, name: 'UBCFIE'},
  {bits:  1, name: 'SPELP'},
  {bits:  1, name: 'MPELP'},
  {bits:  5, name: 'WPRI'},
  {bits:  2, name: 'UXL[1:0]'},
  {bits:  2, name: 'SXL[1:0]'},
  {bits:  1, name: 'SBE'},
  {bits:  1, name: 'MBE'},
  {bits: 25, name: 'WPRI'},
  {bits:  1, name: 'SD'},
], config:{lanes: 4, hspace:1024}}
....

The Zicfiss extension introduces the `UBCFIE` (bit 24) field in `mstatus`. When
`UBCFIE` field is 1, the Zicfiss extension is active in U-mode. When `UBCFIE`
field is 0, the Zicfiss extension is not active in U-mode and the following
rules apply to U-mode.

* Attempts to access the `ssp` CSR raise an illegal-instruction exception.
* The 32-bit Zicfiss instructions revert to their Zimop defined behavior.
* The 16-bit Zicfiss instructions revert to their Zcmop defined behavior.

The Zicfilp extension introduces the `UFCFIE` (bit 23), `SPELP` (bit 25), and
`MPELP` (bit 26) fields in `mstatus`. When `UFCFIE` field is 1, the Zicfilp
extension is active in U-mode. When `UFCFIE` field is 0, the Zicfilp extension
is not active in U-mode and the following rules apply to U-mode.

* The hart does not update the expected landing pad (`ELP`) state and the `ELP`
  state is always `NO_LP_EXPECTED`.
* The `lpad` instruction executes as a no-op.

The `SPELP` (bit 25) and `MPELP` (bit 26) are fields that hold the previous
`ELP`, and are updated as specified in <<FORWARD_TRAPS>>. The `xPELP` fields are
encoded as follows:

* 0 - `NO_LP_EXPECTED` - no landing pad instruction expected.
* 1 - `LP_EXPECTED` - a landing pad instruction is expected.

=== Supervisor status registers (`sstatus`)

.Supervisor-mode status register (`sstatus`) when `SXLEN=64`
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SIE'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'SPIE'},
  {bits:  1, name: 'UBE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SPP'},
  {bits:  2, name: 'VS[1:0]'},
  {bits:  2, name: 'WPRI'},
  {bits:  2, name: 'FS[1:0]'},
  {bits:  2, name: 'XS[1:0]'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SUM'},
  {bits:  1, name: 'MXR'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'UFCFIE'},
  {bits:  1, name: 'UBCFIE'},
  {bits:  1, name: 'SPELP'},
  {bits:  6, name: 'WPRI'},
  {bits:  2, name: 'UXL[1:0]'},
  {bits: 29, name: 'WPRI'},
  {bits:  1, name: 'SD'},
], config:{lanes: 4, hspace:1024}}
....

Access to `UBCFIE` (bit 24) field introduced by Zicfiss accesses the homonymous
field of `mstatus` when `V=0` and the homonymous field of `vsstatus` when `V=1`.

Access to the following fields introducecd by Zicfilp accesses the homonymous
fields of `mstatus` when `V=0` and the homonymous fields of `vsstatus` when `V=1`.

* `UFCFIE` (bit 23).
* `SPELP` (bit 25).

=== Virtual supervisor status registers (`vsstatus`)

.Virtual supervisor status register (`vsstatus`) when `VSXLEN=64`
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SIE'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'SPIE'},
  {bits:  1, name: 'UBE'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SPP'},
  {bits:  2, name: 'VS[1:0]'},
  {bits:  2, name: 'WPRI'},
  {bits:  2, name: 'FS[1:0]'},
  {bits:  2, name: 'XS[1:0]'},
  {bits:  1, name: 'WPRI'},
  {bits:  1, name: 'SUM'},
  {bits:  1, name: 'MXR'},
  {bits:  3, name: 'WPRI'},
  {bits:  1, name: 'UFCFIE'},
  {bits:  1, name: 'UBCFIE'},
  {bits:  1, name: 'SPELP'},
  {bits:  6, name: 'WPRI'},
  {bits:  2, name: 'UXL[1:0]'},
  {bits: 29, name: 'WPRI'},
  {bits:  1, name: 'SD'},
], config:{lanes: 4, hspace:1024}}
....

The Zicfiss extension introduces the `UBCFIE` (bit 24) field in `vsstatus`. When
`UBCFIE` field is 1, Zicfiss extension is active in VU-mode. When `UBCFIE` field
is 0, the following rules apply to VU-mode.

* Attempts to access the `ssp` CSR raise an illegal-instruction exception.
* The 32-bit Zicfiss instructions revert to their Zimop defined behavior.
* The 16-bit Zicfiss instructions revert to their Zcmop defined behavior.

The Zicfilp extension introduces the `UFCFIE` (bit 23) and the `SPELP` (bit 25)
fields in `mstatus`. When `UFCFIE` field is 1, the Zicfilp extension is active
in VU-mode. When `UFCFIE` field is 0, the Zicfilp extension is not active in
VU-mode and the following rules apply to VU-mode.

* The hart does not update the expected landing pad (`ELP`) state and the `ELP`
  state is always `NO_LP_EXPECTED`.
* The `lpad` instruction executes as a no-op.

The `SPELP` (bit 25) are field that hold the previous `ELP`, and is updated as
specified in <<FORWARD_TRAPS>>. The `SPELP` field is encoded as follows:

* 0 - `NO_LP_EXPECTED` - no landing pad instruction expected.
* 1 - `LP_EXPECTED` - a landing pad instruction is expected.

=== Shadow stack pointer (`ssp`) 

The `ssp` CSR is an unprivileged read-write (URW) CSR that reads and writes `XLEN`
low order bits of the shadow stack pointer (`ssp`). There is no high CSR defined
as the `ssp` is always as wide as the `XLEN` of the current privilege mode.

=== Machine Security Configuration (`mseccfg`)

.Machine security configuration register (`mseccfg`) when `MXLEN=64`
[wavedrom, ,svg]
....
{reg: [
  {bits:  1, name: 'MML'},
  {bits:  1, name: 'MMWP'},
  {bits:  1, name: 'RLB'},
  {bits:  5, name: 'WPRI'},
  {bits:  1, name: 'USEED'},
  {bits:  1, name: 'SSEED'},
  {bits:  1, name: 'MFCFIE'},
  {bits:  6, name: 'SSPMP'},
  {bits: 47, name: 'WPRI'},
], config:{lanes: 4, hspace:1024}}
....

The Zicfiss extension introduces the `SSPMP` WARL field in `mseccfg`. The
`SSPMP` field identifies a PMP entry as the shadow stack memory region for
M-mode use. The rules enforced by PMP for M-mode shadow stack memory accesses
are specified in <<PMP_SS>>.

The Zicfilp extension introduces the `MFCFIE` (bit 10) field in `mseccfg`. When
`MFCFIE` field is 1, Zicfilp extension is active in M-mode. When `MFCFIE` field
is 0, the Zicfilp extension is not active in M-mode and the following rules
apply to M-mode.

* The hart does not update the expected landing pad (`ELP`) state and the `ELP`
  state is always `NO_LP_EXPECTED`.
* The `lpad` instruction executes as a no-op.

=== Debug Control and Status (`dcsr`)

.Debug Control and Status (`dcsr`)
[wavedrom, ,svg]
....
{reg: [
  {bits:  2, name: 'prv'},
  {bits:  1, name: 'step'},
  {bits:  1, name: 'nmip'},
  {bits:  1, name: 'mprven'},
  {bits:  1, name: 'v'},
  {bits:  3, name: 'cause'},
  {bits:  1, name: 'stoptime'},
  {bits:  1, name: 'stopcount'},
  {bits:  1, name: 'stepie'},
  {bits:  1, name: 'ebreaku'},
  {bits:  1, name: 'ebreaks'},
  {bits:  1, name: '0'},
  {bits:  1, name: 'ebreakm'},
  {bits:  1, name: 'ebreakvu'},
  {bits:  1, name: 'ebreakvs'},
  {bits:  1, name: 'pelp'},
  {bits:  9, name: '0'},
  {bits:  4, name: 'debugver'},
], config:{lanes: 4, hspace:1024}}
....

The Zicfilp extension introduces the `pelp` (bit 18) in `dcsr`. The `pelp` field
holds the previous `ELP`, and is updated as specified in <<FORWARD_TRAPS>>. The
`pelp` field is encoded as follows:

* 0 - `NO_LP_EXPECTED` - no landing pad instruction expected.
* 1 - `LP_EXPECTED` - a landing pad instruction is expected.
